### ISSUE TITLE
revisit sdp local code gen

### ISSUE THREAD

**Issue by DavidS-ovm** [overmindtech/sdp#299]
Address the symlink issue papered over in https://github.com/overmindtech/sdp/pull/298

**Comment by tphoney** [comment]
How sdp 'npx buf generate' works .
in the gen folder there are symlinks to both the sdp-go and sdp-js.
when generates completes the symlink for sdp-go is broken, sdp-js is ok. 
this means that no changes made in sdp, are propagated through to any of the go projects.

there are 2 config files for "npx buf" buf.gen.yaml and buf.yaml.
we use a plugin to generate the go, maybe this is the smoking gun. 
```
version: v2
clean: true
plugins:
  - local: protoc-gen-go
    out: gen/sdp-go
    opt: paths=source_relative
  - local: protoc-gen-connect-go
    out: gen/sdp-go
    opt: paths=source_relative
```
